Repository Duaily/backend, pull requests merged in 2022-10, with the labels that each got.

#5 [CHORE] 도커 환경세팅 오류 해결
  build.gradle
  src/main/resources/application.yml
Labels: chore

#7 feat: local register
  build.gradle
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/domain/User.java
  src/main/java/com/kusitms/backend/dto/AuthDto.java
  src/main/java/com/kusitms/backend/repository/UserRepository.java
  src/main/java/com/kusitms/backend/service/AuthService.java
Labels: enhancement

#10 [FEAT] 로컬 로그인 구현 및 머지 충돌 해결
  .gitignore
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/config/CustomUserDetailService.java
  src/main/java/com/kusitms/backend/config/JwtAccessDeniedHandler.java
  src/main/java/com/kusitms/backend/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/kusitms/backend/config/JwtFilter.java
  src/main/java/com/kusitms/backend/config/JwtSecurityConfig.java
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/main/java/com/kusitms/backend/config/SecurityUtil.java
  src/main/java/com/kusitms/backend/config/TokenProvider.java
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/domain/Authority.java
  src/main/java/com/kusitms/backend/domain/MetaEntity.java
  src/main/java/com/kusitms/backend/domain/User.java
  src/main/java/com/kusitms/backend/dto/AuthDto.java
  src/main/java/com/kusitms/backend/dto/SignInRequest.java
  src/main/java/com/kusitms/backend/dto/TokenDto.java
  src/main/java/com/kusitms/backend/exception/ApiException.java
  src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
  src/main/java/com/kusitms/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/kusitms/backend/repository/UserRepository.java
  src/main/java/com/kusitms/backend/response/BaseResponse.java
  src/main/java/com/kusitms/backend/response/ExceptionResponse.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/service/IAuthService.java
  src/main/java/com/kusitms/backend/util/RedisClient.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: enhancement, chore

#11 [CHORE] 도메인 생성
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/domain/Address.java
  src/main/java/com/kusitms/backend/domain/Authority.java
  src/main/java/com/kusitms/backend/domain/Comment.java
  src/main/java/com/kusitms/backend/domain/Deal.java
  src/main/java/com/kusitms/backend/domain/House.java
  src/main/java/com/kusitms/backend/domain/HousePost.java
  src/main/java/com/kusitms/backend/domain/ImageFile.java
  src/main/java/com/kusitms/backend/domain/Notice.java
  src/main/java/com/kusitms/backend/domain/Post.java
  src/main/java/com/kusitms/backend/domain/Region.java
  src/main/java/com/kusitms/backend/domain/RegionPost.java
  src/main/java/com/kusitms/backend/domain/ReviewPost.java
  src/main/java/com/kusitms/backend/domain/Tour.java
  src/main/java/com/kusitms/backend/domain/User.java
  src/main/resources/application-local.yml
Labels: chore

#13 [FEAT] 빈 집 게시글 생성 API
  src/main/java/com/kusitms/backend/BackendApplication.java
  src/main/java/com/kusitms/backend/config/JwtAccessDeniedHandler.java
  src/main/java/com/kusitms/backend/config/TokenProvider.java
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/domain/Address.java
  src/main/java/com/kusitms/backend/domain/Comment.java
  src/main/java/com/kusitms/backend/domain/House.java
  src/main/java/com/kusitms/backend/domain/HousePost.java
  src/main/java/com/kusitms/backend/domain/ImageFile.java
  src/main/java/com/kusitms/backend/domain/Post.java
  src/main/java/com/kusitms/backend/domain/Region.java
  src/main/java/com/kusitms/backend/domain/RegionPost.java
  src/main/java/com/kusitms/backend/domain/User.java
  src/main/java/com/kusitms/backend/dto/HouseDto.java
  src/main/java/com/kusitms/backend/repository/HouseRepository.java
  src/main/java/com/kusitms/backend/repository/ImageFileRepository.java
  src/main/java/com/kusitms/backend/repository/PostRepository.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IHouseService.java
Labels: bug, enhancement, chore

#16 [CHORE] Rest Docs 세팅
  .gitignore
  build.gradle
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/config/JwtAccessDeniedHandler.java
  src/main/java/com/kusitms/backend/config/JwtAuthInterceptor.java
  src/main/java/com/kusitms/backend/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/kusitms/backend/config/JwtFilter.java
  src/main/java/com/kusitms/backend/config/JwtSecurityConfig.java
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/main/java/com/kusitms/backend/config/TokenProvider.java
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/dto/TokenDto.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/service/IAuthService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/kusitms/backend/ApiDocumentUtils.java
  src/test/java/com/kusitms/backend/BackendApplicationTests.java
  src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: bug, documentation, test, chore

#17 [FEAT] AWS S3 환경 세팅 및 이미지 업로드 | 삭제 기능 구현
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/config/JwtAccessDeniedHandler.java
  src/main/java/com/kusitms/backend/config/JwtAuthInterceptor.java
  src/main/java/com/kusitms/backend/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/kusitms/backend/config/JwtFilter.java
  src/main/java/com/kusitms/backend/config/JwtSecurityConfig.java
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/main/java/com/kusitms/backend/config/TokenProvider.java
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/controller/S3Controller.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/service/IAuthService.java
  src/main/java/com/kusitms/backend/service/IS3Service.java
  src/main/java/com/kusitms/backend/service/S3Service.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
Labels: enhancement, chore

#19 [FEAT] 지역 생성 API
  src/main/java/com/kusitms/backend/controller/RegionController.java
  src/main/java/com/kusitms/backend/domain/HousePost.java
  src/main/java/com/kusitms/backend/domain/Region.java
  src/main/java/com/kusitms/backend/dto/HouseDto.java
  src/main/java/com/kusitms/backend/dto/RegionDto.java
  src/main/java/com/kusitms/backend/repository/RegionRepository.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IRegionService.java
  src/main/java/com/kusitms/backend/service/RegionService.java
Labels: enhancement

#22 [FEAT] 로컬 로그인 + JWT + Redis
  src/main/java/com/kusitms/backend/config/JwtFilter.java
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/main/java/com/kusitms/backend/config/SecurityUtil.java
  src/main/java/com/kusitms/backend/config/TokenProvider.java
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/dto/TokenDto.java
  src/main/java/com/kusitms/backend/dto/TokenRequestDto.java
  src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/service/IAuthService.java
  src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
Labels: bug, documentation, enhancement
