Repository Duaily/backend, pull requests merged in 2022-11, with the labels that each got.

#26 [FEAT] 소셜 로그인 - 카카오
  build.gradle
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/domain/User.java
  src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
  src/main/java/com/kusitms/backend/repository/UserRepository.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/service/IAuthService.java
  src/main/resources/application-local.yml
Labels: enhancement

#37 [TEST] 전화번호 인증코드 전송 & 검증 API 문서화
  .gitignore
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/dto/CheckSmsRequest.java
  src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
Labels: documentation

#39 [TEST] 빈 집 게시글 작성 API 문서화
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/dto/HouseDto.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: documentation

#43 [TEST] AWS S3 이미지 업로드 & 삭제 API 문서화
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/S3ControllerTest.java
Labels: documentation

#46 [FEAT] 거래 생성 API
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/domain/Deal.java
  src/main/java/com/kusitms/backend/domain/DealState.java
  src/main/java/com/kusitms/backend/dto/DealDto.java
  src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
  src/main/java/com/kusitms/backend/repository/DealRepository.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IHouseService.java
Labels: enhancement

#45 Dual 31
  src/main/java/com/kusitms/backend/controller/ReviewController.java
  src/main/java/com/kusitms/backend/domain/Post.java
  src/main/java/com/kusitms/backend/domain/ReviewPost.java
  src/main/java/com/kusitms/backend/dto/ReviewPostDto.java
  src/main/java/com/kusitms/backend/service/IAuthService.java
  src/main/java/com/kusitms/backend/service/ReviewService.java
Labels: enhancement

#49 [FEAT] 거래 완료 API
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/domain/Deal.java
  src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IHouseService.java
Labels: enhancement

#51 [TEST] 거래 생성 API 문서화
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
  src/test/java/com/kusitms/backend/controller/RegionControllerTest.java
Labels: enhancement

#53 [FEAT] 빈 집 게시글 상세 조회 API
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IHouseService.java
Labels: enhancement

#58 [FEAT] 빈 집 게시글 페이징 처리 API
  docker-compose.yml
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/domain/Address.java
  src/main/java/com/kusitms/backend/domain/House.java
  src/main/java/com/kusitms/backend/dto/HousePreviewDto.java
  src/main/java/com/kusitms/backend/repository/HousePostRepository.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IHouseService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/kusitms/backend/controller/AuthControllerTest.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
  src/test/java/com/kusitms/backend/controller/RegionControllerTest.java
Labels: bug, enhancement, chore

#61 [TEST] 빈 집 게시글 목록 조회 API 문서화
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: documentation, chore

#67 Dual 32
  src/main/java/com/kusitms/backend/controller/ReviewController.java
  src/main/java/com/kusitms/backend/dto/ReviewPostDto.java
  src/main/java/com/kusitms/backend/repository/ReviewPostRepository.java
  src/main/java/com/kusitms/backend/service/ReviewService.java
Labels: enhancement

#74 test: Create get review post detail API docs file
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/ReviewControllerTest.java
Labels: documentation, test

#75 test: Create get review post list API docs file
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/ReviewControllerTest.java
Labels: documentation, test

#85 feat: Create get region post detail api
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/main/java/com/kusitms/backend/controller/RegionController.java
  src/main/java/com/kusitms/backend/service/IRegionService.java
  src/main/java/com/kusitms/backend/service/RegionService.java
Labels: enhancement

#89 Dual 62, Dual 68
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/domain/Category.java
  src/main/java/com/kusitms/backend/domain/House.java
  src/main/java/com/kusitms/backend/domain/Price.java
  src/main/java/com/kusitms/backend/dto/HouseDto.java
  src/main/java/com/kusitms/backend/dto/HousePreviewDto.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
  src/test/java/com/kusitms/backend/controller/ReviewControllerTest.java
Labels: documentation, test

#80 [TEST] CI/CD Test -2
  .github/release-drafter.yml
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  .github/workflows/release-drafter.yml
  Dockerfile
  docker-compose-local.yml
  docker-compose.yml
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/InitUser.java
  src/main/java/com/kusitms/backend/config/RedisConfig.java
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/main/java/com/kusitms/backend/controller/AuthController.java
  src/main/java/com/kusitms/backend/controller/RegionController.java
  src/main/java/com/kusitms/backend/domain/Category.java
  src/main/java/com/kusitms/backend/domain/House.java
  src/main/java/com/kusitms/backend/domain/Price.java
  src/main/java/com/kusitms/backend/dto/HouseDto.java
  src/main/java/com/kusitms/backend/dto/HousePreviewDto.java
  src/main/java/com/kusitms/backend/service/IRegionService.java
  src/main/java/com/kusitms/backend/service/RegionService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
  src/test/java/com/kusitms/backend/controller/ReviewControllerTest.java
Labels: chore

#95 [CHORE] README에 커밋컨벤션 내용 추가
  README.md
Labels: chore

#96 [CHORE] 리드미 수정
  .github/workflows/release-drafter.yml
  README.md
Labels: chore

#105 [DOCS] 빈 집 게시글 문서화 코드 수정
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/kusitms/backend/config/SecurityConfig.java
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: documentation, test, chore

#107 [REFACTOR] 문서화 코드 수정
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: documentation, test

#130 [FIX] 토큰 재발급 API 수정
  src/main/java/com/kusitms/backend/config/TokenProvider.java
  src/main/java/com/kusitms/backend/service/AuthService.java
Labels: bug

#139 [FEAT] 내가 작성한 빈 집 게시글 리스트 조회 API
  src/main/java/com/kusitms/backend/controller/HouseController.java
  src/main/java/com/kusitms/backend/exception/ApiExceptionEnum.java
  src/main/java/com/kusitms/backend/repository/HousePostRepository.java
  src/main/java/com/kusitms/backend/service/HouseService.java
  src/main/java/com/kusitms/backend/service/IHouseService.java
Labels: enhancement

#141 [DOCS] 본인이 작성한 빈 집 게시글 목록 조회 API 문서화
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: documentation, test

#144 Dual 138
  src/main/java/com/kusitms/backend/controller/UserController.java
  src/main/java/com/kusitms/backend/dto/UserDto.java
  src/main/java/com/kusitms/backend/service/IUserService.java
  src/main/java/com/kusitms/backend/service/UserService.java
Labels: enhancement

#146 test: Create get user information API docs
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/UserControllerTest.java
Labels: documentation, test

#149 test: Create get house post detail API docs
  src/docs/asciidoc/api-doc.adoc
  src/test/java/com/kusitms/backend/controller/HouseControllerTest.java
Labels: documentation, test

#151 [FIX] 전화번호 등록 여부 확인 로직 수정
  src/main/java/com/kusitms/backend/repository/UserRepository.java
  src/main/java/com/kusitms/backend/service/AuthService.java
  src/main/java/com/kusitms/backend/util/OauthClient.java
Labels: bug

#155 [DOCS] README 내용 수정
  README.md
Labels: documentation
